FROM node:lts-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY ["./FFT.Frontend/package.json", "."]
COPY ["./FFT.Frontend/package-lock.json", "."]
RUN npm install
COPY ["./FFT.Frontend", "."]
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]