services:
  service:
    build:
        context: .
        dockerfile: Dockerfile.local
    container_name: fft-account-service-local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - MONGODB_CONNSTRING=account_mongo_db://admin:secret@account_mongo_db
    ports:
      - 5001:5001
    depends_on:
      - database
    networks:
      - fft-network
      
  database:
    image: mongo:latest
    container_name: account_mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    # volumes:
    #  - mongo-data:/data/db
    networks:
      - fft-network

#volumes:
#  mongo_data:

networks:
    fft-network:
        external: true