services:
  web-api:
    build: .
    container_name: fft-account-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - 5001:5001

networks:
  default:
    external:
      name: fft-network
