services:
  web-api:
    build: .
    container_name: fft-post-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
    ports:
      - 5002:5002

networks:
  default:
    external:
      name: fft-network
