services:
  service:
    build:
        context: .
        dockerfile: Dockerfile.local
    container_name: fft-post-service-local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MONGODB_CONNSTRING=post_mongo_db://admin:secret@post_mongo_db
    ports:
      - 5002:5002
    depends_on:
      - database
    networks:
      - fft-network
      
  database:
    image: mongo:latest
    container_name: post_mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    # volumes:
    #  - mongo-data:/data/db
    networks:
      - fft-network

#volumes:
#  mongo_data:

networks:
  fft-network:
    external: true